<?php

return [
    ["id" => 1, "name" => "新闻", "alias" => "xinwen"],
    ["id" => 2, "name" => "社会", "alias" => "shehui"],
    ["id" => 3, "name" => "搞笑", "alias" => "gaoxiao"],
    ["id" => 4, "name" => "汽车", "alias" => "qiche"],
    ["id" => 5, "name" => "娱乐", "alias" => "yule"],
    ["id" => 6, "name" => "军事", "alias" => "junshi"],
    ["id" => 7, "name" => "体育", "alias" => "tiyu"],
    ["id" => 8, "name" => "财经", "alias" => "caijing"],
    ["id" => 9, "name" => "科技", "alias" => "keji"],
    ["id" => 10, "name" => "数码", "alias" => "shuma"],
    ["id" => 11, "name" => "健康", "alias" => "jiankang"],
    ["id" => 12, "name" => "时尚", "alias" => "shishang"],
    ["id" => 13, "name" => "旅游", "alias" => "luyou"],
    ["id" => 14, "name" => "企业", "alias" => "qiye"],
    ["id" => 15, "name" => "生活", "alias" => "shenghuo"],
    ["id" => 16, "name" => "教育", "alias" => "jiaoyu"],
    ["id" => 17, "name" => "亲子", "alias" => "qinzi"],
    ["id" => 18, "name" => "游戏", "alias" => "youxi"],
    ["id" => 19, "name" => "文学", "alias" => "wenxue"],
    ["id" => 20, "name" => "美食", "alias" => "meishi"],
    ["id" => 21, "name" => "历史", "alias" => "lishi"],
    ["id" => 22, "name" => "综合", "alias" => "zonghe"],
];
